---
output:
  bookdown::pdf_book:
    toc : no
    keep_tex: no
    number_sections: yes
---

<!-- This section is mandatory! -->

<!-- Proposal -->

Accurate models of multivariate data are highly desired and of great importance in a variety of applications such as financial risk management \citep{McNeil2015}, building science and \mbox{engineering \citep{Dukhan2021, Chen2019}}, hydrology and climatology \citep{Maity2018} just to name a few. In fact, it is reasonable to assume that any natural phenomenon studied in detail usually depends on more than one factor, and nature is multivariate \mbox{\citep[Ch. 2]{Bohm2013}}.

The multivariate normal distribution serves as a fundamental building block in classical multivariate statistics due to its mathematical tractability, but is constrained by elliptical symmetry and light-tailed behavior rendering it an inappropriate model for datasets exhibiting asymmetry or heavy-tailed behavior. Many datasets in fields such as insurance, finance, data networks, econometrics, psychometrics, and climatology exhibit asymmetry and/or heavy-tailed behavior \mbox{\citep{Genton2004, Resnick2007}} so that extensions of the multivariate normal distribution are desired to model characteristics common in real world data.

Elliptically-contoured or elliptical distributions introduced by \mbox{\citet{Kelker1970}} and discussed in detail by \mbox{\citet{Fang1990}} generalize the multivariate normal to allow for both heavy and light-tailed behaviors. The class of elliptical distributions includes distribution families characterized by density level sets that are ellipsoids such as the multivariate normal, multivariate $t$, multivariate logistic, and multivariate exponential power families. Elliptical distributions are commonly used to model financial data such as stock returns and risk \mbox{\citep{McNeil2015}} where the elliptical symmetry constraint might be reasonable.

The \ac{pdf} of a random vector $\Xb \in \R^p$ with an elliptical distribution can be written as \eeq[elliptical-pdf]{
  \fnc{f}{\xb} = \fnc{f_0}{\fnc{\de}{\xb; \mub, \Sigma}; \gbm},
} where \mbox{$\Sigma \in \R^{p\times p}$} is a positive-definite matrix determining the shape of the ellipsoidal density level sets, $\mub \in \R^p$ is the location parameter and ${f_0:[0, \nf)\to(0, \nf)}$ is a decreasing function called the density generator with finite parameter vector $\gbm$ that controls the decay of the density.

We define density level sets for a continuous density $f$ as \eeq[density-level-set]{
  \set{f > c} \coloneqq \set{\xb \in \R^p : \fnc{f}{\xb} > c} = s_c D, \qquad 0 < c < c_0 \coloneqq \sup f,
} where $s_c$ is a positive real number corresponding to $\fnc{f}{\xb} = c$, and the set $D$ is called the shape set. For elliptical distributions, the shape set is given by \eqq{
  D = \set{\xb \in \R^p : \fnc{\de}{\xb; \mub, \Sigma} < 1}.
}

By rewriting the density of an elliptical distribution as in Equation \nolinebreak\eqref{Eq:elliptical-pdf}, it is clear that each point on the boundary of a density level set, $\set{\xb \in \R^p : \fnc{\de}{\xb; \mub, \Sigma} = s_c}$, produces the same density value, $\fnc{f}{\xb} = c$. As a result, the \ac{pdf} of an elliptical distribution is completely determined by $\Sigma$ which analytically describes the shape of the density level sets, $\mub$ which gives the location of the center of the density level sets, and $s_c$ which specifies a density level set by its "distance" from $\mub$. Thus, density level sets are scaled copies of the shape set.

Using the transformation $\de:\R^p\to\R$, Equation \eqref{Eq:elliptical-pdf} demonstrates how the multivariate elliptical density can be rewritten as a density for the random variable $\fnc{\de}{\Xb; \mub, \Sigma}$. As examples, we use Equation \eqref{Eq:elliptical-pdf} to rewrite the bivariate normal and bivariate $t$ densities. Suppose $\mub \in \R^p$ and $\Sigma \in \R^{p\times p}$ are given. The bivariate normal \ac{pdf} can be written as \begin{align*}
  \fnc{f}{\xb; \mub, \Sigma} &= k_1\expo{-\frac{1}{2}\paren{\xb - \mub}\tr\Sigma^{-1}\paren{\yb - \mub}}
    = k_1\expo{-\frac{\fnc{\de}{\xb; \mub, \Sigma}^2}{2}} 
    = \fnc{f_{01}}{\fnc{\de}{\xb; \mub, \Sigma}},
  \end{align*}
for normalizing constant $k_1$ and density generator $f_{01}$. Similarly, the bivariate $t$ \ac{pdf} can be written as \begin{align*}
  \fnc{f}{\xb; \mub, \Sigma, \nu} &= k_2\brac{1 + \frac{1}{\nu}\paren{\xb - \mub}\tr\Sigma^{-1}\paren{\xb - \mub}}^{-\frac{\nu + 2}{2}}
    = k_2\brac{1 + \frac{\fnc{\de}{\xb; \mub, \Sigma}^2}{\nu}}^{-\frac{\nu + 2}{2}} 
    = \fnc{f_{02}}{\fnc{\de}{\xb; \mub, \Sigma}},
  \end{align*}
for normalizing constant $k_2$ and density generator $f_{02}$.

For an elliptically distributed random vector $\Xb$, consider the transformations \eqq{
  R = \fnc{\de}{\Xb; \mub, \Sigma} \qquad \text{and} \qquad \T = \frac{\Xb}{R},
} where $R$ is the Mahalanobis distance of $\Xb$ from $\mub$ and $\T$ is its direction. Random variables $R$ and $\T$ are independent \mbox{\citep{Kamiya2008}}. For a fixed $\Sigma$, the distribution of $\T$ is the same for all elliptically contoured distributions, so we can construct arbitrary elliptical distributions by changing the distribution of $R$. This property, often referred to as null robustness \citep{Kariya1989}, states that distributional results concerning $\T$ derived under the assumption of normality continue to hold for all elliptical distributions having the same \mbox{$\Sigma$ \citep{Kamiya2008}}. We can thus view density estimation for an elliptical distribution as a two-step procedure that estimates the independent distributions of $R$ and $\T$.

Unfortunately, the elliptical distributions are too narrow in scope as they only differ from the multivariate normal distribution through the distribution of $R$ and cannot model data exhibiting skewness or asymmetry due to the elliptical symmetry constraint. Scatterplots of multivariate data frequently display shapes of contour lines/surfaces that are not ellipses/ellipsoids \citep{Liebscher2020} and despite the popularity of elliptical distributions for modelling financial data, stock returns are not necessarily \mbox{elliptical \citep{Chicheportiche2012}}. Hence, a generalization of elliptical distributions is needed.

As shown in \citet{Kamiya2008}, the independence of distance and direction as well as null robustness continue to hold beyond the elliptical distributions so long as the notion of distance is defined properly. The need for flexibility beyond the elliptical distributions and the properties of independence of distance and direction and null robustness motivate the development of the class of star-shaped distributions whose densities have level sets that are scaled copies of some arbitrary star-shaped set.

Star-shaped distributions \citep{Kamiya2008} comprise a highly flexbile class of distributions that generalize the elliptical class by removing the elliptical symmetry constraint and allow for density level sets to be scaled copies of any star-shaped set. A set $D$ is star-shaped with respect to $\mub$ if $\xb\in D$ implies $\xi\xb + \paren{1-\xi}\mub \in D$ for all $0 < \xi < 1$. This class was previously studied as the $\nu$-spherical class \citep{Fernandez1995} and the directionally dispersed class ($D$-class) \citep{Ferreira2005}.

In this thesis, we focus on a sub-class of star-shaped distributions characterized by having continuous density functions with homothetic level sets. These densities are referred to as homothetic \mbox{densities \citep{Balkema2010}} and have density level sets that are scaled copies of some star-shaped set $D$ with respect to a center $\mub$ analytically described by \mbox{function $n_D:\R^p \to [0, \nf)$} called a gauge function that is homogeneous of degree $1$ \mbox{and $D = \set{\xb \in \R^p | \fnc{n_D}{\xb - \mub} < 1}$} is an open, bounded set. In addition, we assume that for each vector \mbox{$\paren{\xb-\mub} \in D$}, there is one positive real $r$ such \mbox{that $r\cdot\paren{\xb-\mub}$} lies on the boundary of $D$. This assures a continuous gauge function on the open cone $D_{\nf} = \bigcup_n nD$.

A density $f$ on $\R^p$ is said to belong to the class of homothetic densities, denoted $f \in \HC{D}$, if the shape set $D$ is a bounded open star-shaped set in $\R^p$ and if $f$ has the following representation, \eeq[star-pdf]{
  \fnc{f}{\xb} = \fnc{f_0}{\fnc{n_D}{\xb - \mub}},
} where $f_0:[0, \nf) \to (0, \nf)$ is a decreasing continuous function called the density generator. Densities for the elliptical distributions belong to $\HC{D}$ with gauge function $\fnc{n_D}{\xb - \mub} = \fnc{\de}{\xb; \mub, \Sigma}$.

For random vector $\Xb \in \R^p$ with \ac{pdf} $f \in \HC{D}$, we use the following transformations of $\Xb$ to create variables for distance and direction, respectively, \eqq{
  R = \fnc{n_D}{\Xb - \mub} \qquad \text{and} \qquad \T = \frac{\Xb}{R},
} where $R$ is the star-generalized radius variable \citep{Liebscher2016} corresponding to $\Xb$ and $\T$ is its direction. Homothetic densities thus generalize the elliptical distributions through these notions of distance and direction that preserve independence of $R$ and $\T$ as well as null robustness on the distribution of $\T$.

There are three main goals of this research. The first is to review, implement, and critique various approaches for estimating distributions from multivariate datasets assumed to have homothetic densities. We start with a focus on $\R^2$ since methods that perform poorly in $\R^2$ are unlikely to generalize to higher dimensions. We also propose a parametric subclass of distributions with homothetic densities called trochoidal distributions that generalize the elliptical class. The second is to analyze the asymptotic behavior of multivariate risk measures popular in finance and insurance when risk factors have a joint \ac{pdf} $f\in\HC{D}$ with a light-tailed density generator. Finally, we plan to investigate the estimation of high-risk regions for homothetic densities usually requiring extrapolation beyond the observed data.

The remainder of this report is outlined as follows: the first major research objective is presented in detail in Section \@ref(SS:intro-modelling). Section \@ref(S:background) provides definitions, results, and properties that facilitate a formal discussion of the class of homothetic densities and motivate approaches for estimation. Section \@ref(S:shape-set) discusses nonparametric and semiparametric approaches for estimating the shape set and presents preliminary results on simulated data. We introduce an iterative approach for density estimation in Section \@ref(S:estimation-dg) and apply this approach on a simulated dataset. Section \@ref(SS:trochoidal-dist) introduces the class of trochoidal distributions, comprised of fully parametric families, and performs \ac{ml} estimation to fit candidate families to simulated data. Finally, Section \@ref(S:objectives) discusses remaining work to be completed and presents a summary of the literature performed for the second primary objective on the asymptotic behavior of multivariate financial risk measures.

<!-- Remove these to be completed sections to the end -->
<!-- ## Estimation of High Risk Regions for Light-tailed Random Vectors {#SS:intro-risk-regions} -->

<!-- Work is not yet underway on this objective. -->


<!-- Despite the approach outlined in the previous paragraph, there are no strict guidelines or consensus that says we must estimate the shape set first and then the density generator. In addition, various techniques are available for estimating the boundary of the shape set when it is a continuous function through a cloud of data points. Similarly, there are many valid approaches that enable us to estimate $f_0$ as a univariate function of star-generalized radius variables. However, there are no general estimation procedures in the literature able to simultaneously estimate both $D$ and $f_0$ for a distribution $F \in \HC{D}$ when the appropriate parametric forms are not known. Therefore, a primary goal of this research is to compare different procedures in the literature that are appropriate for estimating $f_0$, $n_D$, and $\mub$ individually, and then devise an approach that estimates the distribution $F \in \HC{D}$ by estimating all quantities either sequentially or simultaneously. -->

<!-- A semiparametric and parametric approach to estimating a star-shaped distributon is introduced in \citet{Liebscher2016}. In both instances, the shape set is assumed to be a functional with a known parametric form allowing for maximum likelihood estimation. The semiparametric approach estimates $f_0$ nonparametrically while the fully parametric approach assumes a known parametric form for $f_0$ and estimates all parameters for $f_0$ and $D$ simultaneously. Advantages of the parametric approach are that we can find maximum likelihood estimators which have optimal properties in terms of mean-squared error. However, this requires we know the correct parametric forms. -->

<!-- The desire for parametric forms motivates to the parametric models introduced in \citet{Liebscher2020} which are able to model an impressive range of shape sets using a parsimonious parametric form. Continuing in this vein, we propose the use of epitrochoids to model the shape of density level sets and refer to the class of distributions whose density level sets can be modelled as such as trochoidal distributions. Epitrochoids are functions formed by a generating point of distance $d$ from the center of a circle with radius $r$, called the rolling circle, as it rolls along the outside of a circle with radius $R$ called the fixed circle. We propose that the trochoidal distribution family can generate a wider range of shape sets than those of \citet{Liebscher2016} and \citet{Liebscher2020} using only 3 parameters. Restrictions must be placed on these parameters so that the resulting distributions with trochoidal shape sets are identifiable. -->

<!-- A shortcoming of the classes of star-shaped distributions introduced in \citet{Liebscher2016} and \citet{Liebscher2020} as well as the trochoidal distributions is that they require some sort of symmetry in the data in order to be the appropriate parametric form. However, we propose that the trochoidal class is the most flexible and therefore offers a promising parameterization covering a significant range of distributions in $\HC{D}$. For example, trochoids can be used to model shape sets that are =elliptical or $\ell_q$-norms for $q \in \set{(0, 1], 2, \nf}$. This list is not meant to be exhaustive, but demonstrates that trochoidal distributions can model common shape sets in addition to a wide range of others. -->

<!-- Modeling multivariate data with a distribution $F \in \HC{D}$ is desirable and has certain advantages. First, $\HC{D}$ is a highly flexible class of distributions covering the popular elliptical class while also being able to model complex asymmetric dependence structures in various directions. Second, distributions in $\HC{D}$ have the characteristic of being entirely defined by the quantities $\mub$, $D$, and $f_0$, where given one quantity the others can be interchanged and chosen freely. This reduces a potentially complex optimization problem to a sequence of simpler optimizations for each quantity. Third, since density level sets inherit the shape of $D$, knowledge of $D$ reduces multivariate analysis to a univariate problem involving only the star-generalized radius variables. For example, we can apply univariate extreme value theory to estimate multivariate risk regions with little or no data by using the quantiles of the star-generalized radius variables as opposed to applying multivariate techniques. Thus, a tertiary goal of this research is to perform multivariate analysis on extreme risk regions with applications to finance. -->

<!-- While the bivariate setting is often used to introduce and demonstrate various techniques, a quaternary goal of this research is to generalize to higher dimensions. The literature on estimation of star-shaped distributions in more than 2-dimensions is sparse. In particular, we want to devise and apply techniques that show promising performance in 3-dimensions.  -->

<!-- There are other generalizations of elliptical distributions such as the skew-elliptical distributions \citep{Genton2004} that remove the elliptical restriction on the shape of density level sets. However, the skew-elliptical distributions take a different approach in generalizing elliptical distributions that do not require the decomposition of the roles of vector length and direction in the density. As a result, the skew-elliptical distributions are a separate class of distributions from $\HC{D}$ and are not considered. -->

<!-- The rest of this report is outlined as follows: Section \@ref(background) introduces the notation and definitions as well as justifying some fundamental results needed to perform estimation of distributions in $\HC{D}$. Section \@ref(estimation) outlines the different estimation approaches that are either available in the literature or introduced here for the shape set and the density generating function. Section \@ref(simulation) provides algorithms to reproduce the simulations from this report and analyzes the properties of the simulated datasets to validate the algorithms and discern any unexpected results due to sampling variability. Section \@ref(results) proposes approaches to estimating $F \in \HC{D}$ by analyzing the different techniques of Section \@ref(estimation) and combining estimators for location, shape set, and density generator to find a general approach for estimating the entire distribution. Section \@ref(conclusion) offers a concluding discussion of the most common problems encountered during the course of this research, and how those problems were either overcome or provide areas for future research. -->